version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
  web_app:
    image: nikelwolf/fastapi-realworld
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "80:8000"
