version: '3'

services:
  db:
    image: postgres:11.1
    env_file:
      - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: nikelwolf/fastapi-realworld
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
