version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env.example
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.example
    depends_on:
      - db
    ports:
      - "80:8000"
